"""Initial database schema with User, Quote, Feedback, and Theme models

Revision ID: 392d37558c6b
Revises: 
Create Date: 2025-12-20 18:32:46.841569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392d37558c6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Theme name (e.g., 'Personal Growth', 'Mindfulness')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the theme'),
    sa.Column('type', sa.Enum('monthly', 'weekly', name='themetype'), nullable=False, comment='Whether this is a monthly or weekly theme'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date for this theme period'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End date for this theme period'),
    sa.Column('parent_theme_id', sa.String(length=36), nullable=True, comment='Parent theme (for weekly themes under monthly themes)'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='Keywords associated with this theme'),
    sa.Column('personality_alignment', sa.JSON(), nullable=True, comment='How this theme aligns with different personality categories'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Theme display and behavior configuration'),
    sa.CheckConstraint("type IN ('monthly', 'weekly')", name='valid_theme_type'),
    sa.CheckConstraint('start_date <= end_date', name='valid_date_range'),
    sa.ForeignKeyConstraint(['parent_theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_end_date'), 'themes', ['end_date'], unique=False)
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_index(op.f('ix_themes_parent_theme_id'), 'themes', ['parent_theme_id'], unique=False)
    op.create_index(op.f('ix_themes_start_date'), 'themes', ['start_date'], unique=False)
    op.create_index(op.f('ix_themes_type'), 'themes', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('personality_data', sa.JSON(), nullable=True, comment='Personality categories and weights from questionnaire'),
    sa.Column('notification_settings', sa.JSON(), nullable=True, comment='Push notification preferences'),
    sa.Column('sync_token', sa.String(length=255), nullable=True, comment='Token for data synchronization across devices'),
    sa.Column('preferences', sa.JSON(), nullable=True, comment='User interface and content preferences'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_sync_token'), 'users', ['sync_token'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User who received this quote'),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual quote text content'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='Quote author (if applicable)'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date this quote was delivered'),
    sa.Column('theme_id', sa.String(length=36), nullable=True, comment='Associated theme for this quote'),
    sa.Column('personalization_context', sa.JSON(), nullable=True, comment='Personalization data used for quote generation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date_quote')
    )
    op.create_index(op.f('ix_quotes_date'), 'quotes', ['date'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_theme_id'), 'quotes', ['theme_id'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False, comment='Quote being rated'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User providing feedback'),
    sa.Column('rating', sa.String(length=10), nullable=False, comment='User rating: like, neutral, or dislike'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True, comment='Additional context about the feedback'),
    sa.CheckConstraint("rating IN ('like', 'neutral', 'dislike')", name='valid_rating'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_quote_id'), 'feedback', ['quote_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_quote_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_theme_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_date'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_users_sync_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_type'), table_name='themes')
    op.drop_index(op.f('ix_themes_start_date'), table_name='themes')
    op.drop_index(op.f('ix_themes_parent_theme_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_end_date'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###